Repository kitten-science/kitten-scientists, pull requests merged in 2023-01, with the labels that each got.

#101 fix(time): Accelerate time goes below stock
  packages/userscript/source/TimeControlManager.ts
Labels: type:bug

#109 fix(village): Not all jobs/traits are assigned as leaders
  packages/userscript/source/settings/ElectLeaderSettings.ts
  packages/userscript/source/settings/Settings.ts
  packages/userscript/source/types/index.ts
Labels: type:bug, prio:important, status:confirmed, status:fixed

#102 feat(time): Turn on Chrono Furnaces
  packages/userscript/source/TimeManager.ts
  packages/userscript/source/i18n/i18nData.json
  packages/userscript/source/settings/TimeSettings.ts
  packages/userscript/source/types/gamePage.ts
  packages/userscript/source/types/time.ts
  packages/userscript/source/ui/TimeSettingsUi.ts
Labels: type:feature, needs:merge

#116 feat(time): Added kitten population as a criteria for autoreset
  packages/userscript/source/settings/ResetResourcesSettings.ts
Labels: prio:important, type:enhancement, status:completed

#110 State Management
  packages/documentation/docs/sections/state-management.md
  packages/documentation/mkdocs.yml
  packages/userscript/package.json
  packages/userscript/source/Engine.ts
  packages/userscript/source/UserScript.ts
  packages/userscript/source/i18n/i18nData.json
  packages/userscript/source/images/Icons.ts
  packages/userscript/source/images/delete_FILL0_wght400_GRAD0_opsz48.svg
  packages/userscript/source/settings/EngineSettings.ts
  packages/userscript/source/settings/StateSettings.ts
  packages/userscript/source/types/gamePage.ts
  packages/userscript/source/ui/EngineSettingsUi.ts
  packages/userscript/source/ui/StateManagementUi.ts
  packages/userscript/source/ui/UserInterface.ts
  packages/userscript/source/ui/components/ExplainerListItem.ts
  packages/userscript/source/ui/components/Panel.ts
  packages/userscript/source/ui/components/SettingListItem.ts
  packages/userscript/source/ui/components/UiComponent.ts
  packages/userscript/source/ui/components/buttons-icon/DeleteButton.ts
  yarn.lock
Labels: type:feature, prio:accepted, needs:work, status:inprogress

#125 feat(workshop): Simplify resource crafting
  packages/documentation/docs/sections/bonfire.md
  packages/documentation/docs/sections/village.md
  packages/documentation/docs/sections/workshop.md
  packages/documentation/mkdocs.yml
  packages/userscript/source/WorkshopManager.ts
  packages/userscript/source/settings/WorkshopSettings.ts
  packages/userscript/source/ui/WorkshopSettingsUi.ts
Labels: type:feature, prio:accepted, needs:testing, status:inprogress

#126 feat(core): Remove hardcoded build requirements
  .vscode/settings.json
  packages/userscript/source/WorkshopManager.ts
  packages/userscript/source/helper/BulkPurchaseHelper.ts
  packages/userscript/source/settings/BonfireSettings.ts
  packages/userscript/source/settings/ReligionSettings.ts
  packages/userscript/source/settings/TimeSettings.ts
Labels: type:feature, prio:accepted, needs:merge, status:inprogress

#129 feat(core): Remove redundant state fields
  packages/userscript/source/settings/BonfireSettings.ts
  packages/userscript/source/settings/BuildingUpgradeSettings.ts
  packages/userscript/source/settings/EmbassySettings.ts
  packages/userscript/source/settings/LogFilterSettings.ts
  packages/userscript/source/settings/MissionSettings.ts
  packages/userscript/source/settings/PolicySettings.ts
  packages/userscript/source/settings/ReligionSettings.ts
  packages/userscript/source/settings/ResetBonfireSettings.ts
  packages/userscript/source/settings/ResetReligionSettings.ts
  packages/userscript/source/settings/ResetResourcesSettings.ts
  packages/userscript/source/settings/ResetSpaceSettings.ts
  packages/userscript/source/settings/ResetTimeSettings.ts
  packages/userscript/source/settings/ResourcesSettings.ts
  packages/userscript/source/settings/SpaceSettings.ts
  packages/userscript/source/settings/TechSettings.ts
  packages/userscript/source/settings/TimeSettings.ts
  packages/userscript/source/settings/TradeSettings.ts
  packages/userscript/source/settings/UpgradeSettings.ts
  packages/userscript/source/settings/WorkshopSettings.ts
Labels: prio:important, type:enhancement, needs:merge, status:completed
