Repository kitten-science/kitten-scientists, pull requests merged in 2025-03, with the labels that each got.

#954 fix: Makefile compatibility with Mac
  Makefile
Labels: prio:important, type:enhancement, needs:merge, type:housekeeping

#951 Implement entire KG API Surface and resolve Regressions
  source/BonfireManager.ts
  source/Engine.ts
  source/KittenScientists.ts
  source/ReligionManager.ts
  source/ScienceManager.ts
  source/SpaceManager.ts
  source/TabManager.ts
  source/TimeControlManager.ts
  source/TimeManager.ts
  source/TradeManager.ts
  source/UpgradeManager.ts
  source/VillageManager.ts
  source/WorkshopManager.ts
  source/helper/BulkPurchaseHelper.ts
  source/settings/MissionSettings.ts
  source/settings/PolicySettings.ts
  source/settings/ReligionSettings.ts
  source/settings/ResetReligionSettings.ts
  source/settings/ScienceSettings.ts
  source/settings/Settings.ts
  source/settings/SpaceSettings.ts
  source/settings/TechSettings.ts
  source/settings/UpgradeSettings.ts
  source/settings/WorkshopSettings.ts
  source/tools/SavegameLoader.ts
  source/types/_releases.ts
  source/types/_save.ts
  source/types/achievements.ts
  source/types/buildings.ts
  source/types/calendar.ts
  source/types/challenges.ts
  source/types/core.ts
  source/types/craft.ts
  source/types/diplomacy.ts
  source/types/game.ts
  source/types/index.ts
  source/types/math.ts
  source/types/prestige.ts
  source/types/religion.ts
  source/types/resources.ts
  source/types/science.ts
  source/types/space.ts
  source/types/stats.ts
  source/types/time.ts
  source/types/toolbar.ts
  source/types/trade.ts
  source/types/ui.ts
  source/types/village.ts
  source/types/void.ts
  source/types/workshop.ts
  source/ui/ReligionSettingsUi.ts
  source/ui/ResetReligionSettingsUi.ts
  source/ui/ResetTimeSettingsUi.ts
  source/ui/StateManagementUi.ts
  source/ui/TimeSettingsUi.ts
  vite.config.inject.js
  vite.config.userscript.js
Labels: type:bug, prio:important, type:enhancement, needs:work, status:inprogress

#957 Introduce more Types
  Makefile
  source/BonfireManager.ts
  source/ReligionManager.ts
  source/SpaceManager.ts
  source/TimeControlManager.ts
  source/TimeManager.ts
  source/UpgradeManager.ts
  source/helper/BulkPurchaseHelper.ts
  source/types/buildings.ts
  source/types/challenges.ts
  source/types/core.ts
  source/types/diplomacy.ts
  source/types/index.ts
  source/types/prestige.ts
  source/types/religion.ts
  source/types/science.ts
  source/types/space.ts
  source/types/time.ts
  source/types/types.gv
  source/types/village.ts
  source/types/workshop.ts
Labels: type:bug, prio:important, type:enhancement, needs:testing, status:inprogress
